大量优化与修正 typo
laserroger/Physics-from-Symmetry pull request #79
Opened 2019-10-27 19:16 UTC by kexplorning

修改简略描述如下：

1. 每个 Part 后面的引用尝试修复（是的，这个魔改成功了，需要在 `\part` 后面立即使用 `partquote` 环境，如果没有这个环境，可能有没有空页的问题）
2. `eps` 图片转换为 `pdf`（PDF 图片兼容性更好）
3. 修正大量标点符号错误（英文引号、中文引号、中文破折号、英文破折号等）
4. 去除各种冗余代码
5. 实现输入 `。` 输出全角点号
6. 前言、目录等增加到书签中
7. 完善 PDF 元数据
8. 修正一些不优雅的数学公式与文本方式（我尽力了……后面那一坨一坨的公式实在修不了）
9. 脚注图片的 hyperref 跳转正确
10. 禁用无关宏包（`babel` `microtype` 等等给西文排版的，还是别开了吧，可能会有奇怪的错误……）
11. 删除临时文件

其余还有一些代码优化。

---

修完后，有一个感想：觉得需要有一份格式标准以及各位是都不知道有 `physics` 这个宏包吗……

……打出后面那这么一大串公式实在有毅力……

---

最后还是感谢，带来了这本书的翻译。问一下，第二版的修订什么时候会开始？

2019-11-01 01:29 UTC, laserroger approved these changes

2019-11-01 01:34 UTC, laserroger requested changes
啊我觉得句号挺好，没必要非得按照英文的. , 来

2019-11-01 01:34 UTC, laserroger commented on TEX File/main.tex
> +
not necessary

2019-11-04 03:08 UTC, kexplorning commented on TEX File/main.tex
> +
呃，这是中文点号，呃，防止与数学记号弄混才搞的……

2019-11-09 17:42 UTC, laserroger commented on TEX File/main.tex
> +
我知道啊，我是说，中文的。一般并不会搞混，而且我个人并不希望使用. 这也不是一个通用习俗（虽然确实有的人使用过）

2019-11-12 04:43 UTC, kexplorning commented on TEX File/main.tex
> +
呃，好吧……

2019-11-14 06:04 UTC, kexplorning commented
。。应该是没问题了吧？

2019-11-21 15:21 UTC, merged